# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'traceData-single.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 600)
        Form.setStyleSheet("*{    \n"
"    font-family:微软雅黑;\n"
"    font-size:25px;\n"
"    color: #1d649c;\n"
"}\n"
"#inputPro {\n"
"    font-size:35px;\n"
"    color: #00aaff\n"
"}\n"
"#btn{\n"
"    background-color: #eeff82;\n"
"    border:1px solid black;\n"
"    font-family: 微软雅黑;\n"
"    font-size: 35px;\n"
"    color: #00aa00\n"
"}\n"
"#btn:hover{\n"
"    opacity:0.2;\n"
"    border:2px solid black;\n"
"}\n"
"#btn:pressed{\n"
"    background-color:transparent;\n"
"    border:1px solid black;\n"
"}\n"
"#inputBox{\n"
"    line-height: 30px;\n"
"}\n"
"#messageDisplay {\n"
"    background-color: #ffff8f;\n"
"    height: 40px;\n"
"}")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.reelNum = QtWidgets.QLabel(Form)
        self.reelNum.setObjectName("reelNum")
        self.horizontalLayout.addWidget(self.reelNum)
        self.reelNumValue = QtWidgets.QLabel(Form)
        self.reelNumValue.setObjectName("reelNumValue")
        self.horizontalLayout.addWidget(self.reelNumValue)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.reelRemain = QtWidgets.QLabel(Form)
        self.reelRemain.setObjectName("reelRemain")
        self.horizontalLayout.addWidget(self.reelRemain)
        self.reelRemainValue = QtWidgets.QLabel(Form)
        self.reelRemainValue.setObjectName("reelRemainValue")
        self.horizontalLayout.addWidget(self.reelRemainValue)
        self.btn = QtWidgets.QPushButton(Form)
        self.btn.setObjectName("btn")
        self.horizontalLayout.addWidget(self.btn)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 4)
        self.horizontalLayout.setStretch(2, 2)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 2)
        self.horizontalLayout.setStretch(5, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.messageDisplay = QtWidgets.QLineEdit(Form)
        self.messageDisplay.setObjectName("messageDisplay")
        self.horizontalLayout_2.addWidget(self.messageDisplay)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 7)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(278, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.logDisplay = QtWidgets.QTextBrowser(Form)
        self.logDisplay.setObjectName("logDisplay")
        self.horizontalLayout_3.addWidget(self.logDisplay)
        spacerItem4 = QtWidgets.QSpacerItem(198, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 6)
        self.horizontalLayout_3.setStretch(2, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.panelSn = QtWidgets.QLabel(Form)
        self.panelSn.setObjectName("panelSn")
        self.horizontalLayout_4.addWidget(self.panelSn)
        self.panelSnValue = QtWidgets.QLabel(Form)
        self.panelSnValue.setObjectName("panelSnValue")
        self.horizontalLayout_4.addWidget(self.panelSnValue)
        spacerItem5 = QtWidgets.QSpacerItem(568, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 3)
        self.horizontalLayout_4.setStretch(2, 6)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.terminalId = QtWidgets.QLabel(Form)
        self.terminalId.setObjectName("terminalId")
        self.horizontalLayout_5.addWidget(self.terminalId)
        self.terminalIdValue = QtWidgets.QLabel(Form)
        self.terminalIdValue.setObjectName("terminalIdValue")
        self.horizontalLayout_5.addWidget(self.terminalIdValue)
        spacerItem6 = QtWidgets.QSpacerItem(288, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.userName = QtWidgets.QLabel(Form)
        self.userName.setObjectName("userName")
        self.horizontalLayout_5.addWidget(self.userName)
        self.userNameValue = QtWidgets.QLabel(Form)
        self.userNameValue.setObjectName("userNameValue")
        self.horizontalLayout_5.addWidget(self.userNameValue)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_5.setStretch(2, 6)
        self.horizontalLayout_5.setStretch(3, 1)
        self.horizontalLayout_5.setStretch(4, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 2)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 2)
        self.verticalLayout.setStretch(5, 1)
        self.verticalLayout.setStretch(6, 1)
        self.horizontalLayout_6.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.reelNum.setText(_translate("Form", "REEL:"))
        self.reelNumValue.setText(_translate("Form", "230-101020-008H201900002"))
        self.reelRemain.setText(_translate("Form", "REEL剩余量:"))
        self.reelRemainValue.setText(_translate("Form", "200"))
        self.btn.setText(_translate("Form", "上料"))
        self.label.setText(_translate("Form", "输入工号："))
        self.panelSn.setText(_translate("Form", "Panel SN:"))
        self.panelSnValue.setText(_translate("Form", "TextLabel"))
        self.terminalId.setText(_translate("Form", "Terminal ID:"))
        self.terminalIdValue.setText(_translate("Form", "111111"))
        self.userName.setText(_translate("Form", "人员："))
        self.userNameValue.setText(_translate("Form", "马金龙"))
